version: '3.7'
services:
  ddm-project:
    container_name: ddm-project
    restart: always
    image: steeven9/ddm-project
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
networks:
  default:
    name: ddm-project
